version: '3'

volumes:
  wolk:

services:
  wolk_db:
    image: mysql:5.6
    container_name: wolk_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - wolk:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123qwe
